spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_SECRET
            scope:
              - email
              - profile
          facebook:
            client-id: YOUR_FACEBOOK_APP_ID
            client-secret: YOUR_FACEBOOK_SECRET
            scope:
              - email
              - public_profile

allowed:
  secret-names:
    - "Fürge Szarvas"
    - "Ülő Bika"
    - "Széllelfutó Ló"
    - "Kócos Bölény"
    - "Merész Párduc"
    - "Bölcs Medve"
    - "Békés Farkas"
    - "Tűzszemű Sólyom"
    - "Szökkenő Nyúl"
    - "Bátor Teknős"
    - "Fényestollú Sas"
    - "Délceg Vidra"
  secret-filenames:
    - "szarvas.png"
    - "bika.png"
    - "lo.png"
    - "boleny.png"
    - "parduc.png"
    - "medve.png"
    - "farkas.png"
    - "solyom.png"
    - "nyul.png"
    - "teknos.png"
    - "sas.png"
    - "vidra.png"