spring.application.name=tippmix

# Postgre SQL settings
spring.datasource.url=jdbc:postgresql://localhost:5432/TIPPMIX
spring.datasource.username=postgres
spring.datasource.password=kesjar
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# to enable JPA can automatically create or update your schema: check entities, compare them with existing tables; create or update tables / columns accordingly
# great for local dev, but don't use it in PROD
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

#server.port=8081

# App specific env vars
ALLOWED_SECRET_NAMES=Fürge Szarvas,Ülő Bika,Fényes Gepárd,Király Kígyó,Örömittas Teknős,Űzött Hiúz

# UTF 8 for Hungarian
spring.messages.encoding=UTF-8
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true